# ETF Universe Configuration
# ETF 完整候选池配置

etf_universe:
  # 游戏动漫文娱
  entertainment:
    - code: "159869"
      name: "游戏ETF"
    - code: "516770"
      name: "动漫游戏ETF"
    - code: "512980"
      name: "传媒ETF"
    - code: "159805"
      name: "传媒ETF（场内）"
    - code: "516620"
      name: "文娱传媒ETF"
  
  # 科技创新
  technology:
    - code: "588000"
      name: "科创50ETF"
    - code: "512720"
      name: "计算机ETF"
    - code: "515000"
      name: "科技ETF"
    - code: "159997"
      name: "电子ETF"
    - code: "512480"
      name: "半导体ETF"
    - code: "516380"
      name: "芯片ETF"
    - code: "159801"
      name: "半导体芯片ETF"
    - code: "159766"
      name: "人工智能ETF"
    - code: "516070"
      name: "云计算ETF"
    - code: "159998"
      name: "计算机ETF（深）"
  
  # 新能源产业链
  new_energy:
    - code: "516160"
      name: "新能源ETF"
    - code: "515790"
      name: "光伏ETF"
    - code: "515030"
      name: "新能源车ETF"
    - code: "159755"
      name: "电池ETF"
    - code: "516660"
      name: "绿电ETF"
    - code: "516850"
      name: "新材料ETF"
    - code: "515700"
      name: "新能车ETF"
    - code: "159757"
      name: "新能源车龙头ETF"
  
  # 消费行业
  consumer:
    - code: "512690"
      name: "酒ETF"
    - code: "159928"
      name: "消费ETF"
    - code: "512600"
      name: "主要消费ETF"
    - code: "159996"
      name: "家电ETF"
    - code: "515650"
      name: "消费50ETF"
    - code: "159736"
      name: "食品饮料ETF"
    - code: "516110"
      name: "汽车ETF"
  
  # 医药健康
  healthcare:
    - code: "512010"
      name: "医药ETF"
    - code: "512170"
      name: "医疗ETF"
    - code: "159929"
      name: "医药ETF（深）"
    - code: "512610"
      name: "医药卫生ETF"
    - code: "159891"
      name: "生物医药ETF"
    - code: "516970"
      name: "创新药ETF"
    - code: "159992"
      name: "创新药沪深港ETF"
  
  # 金融地产
  finance:
    - code: "512000"
      name: "券商ETF"
    - code: "512800"
      name: "银行ETF"
    - code: "512200"
      name: "房地产ETF"
    - code: "159940"
      name: "金融ETF"
    - code: "512070"
      name: "非银ETF"
    - code: "512750"
      name: "保险ETF"
  
  # 周期资源
  cyclical:
    - code: "512400"
      name: "有色金属ETF"
    - code: "515210"
      name: "钢铁ETF"
    - code: "516780"
      name: "稀土ETF"
    - code: "159715"
      name: "有色ETF"
    - code: "159980"
      name: "有色60ETF"
    - code: "159876"
      name: "有色金属ETF（深）"
    - code: "159881"
      name: "煤炭ETF"
  
  # 军工安防
  defense:
    - code: "512760"
      name: "国防军工ETF"
    - code: "516010"
      name: "专精特新ETF"
    - code: "516670"
      name: "军工ETF"
    - code: "512810"
      name: "军工ETF（华宝）"
  
  # 基建出口
  infrastructure:
    - code: "516970"
      name: "基建50ETF"
    - code: "159605"
      name: "出口ETF"
    - code: "516950"
      name: "基建ETF"
    - code: "159619"
      name: "基建工程ETF"
  
  # 核心资产
  core:
    - code: "510300"
      name: "沪深300ETF"
    - code: "159919"
      name: "沪深300ETF（深）"
    - code: "510880"
      name: "红利ETF"
    - code: "511990"
      name: "华宝现金添益"
    - code: "518880"
      name: "黄金ETF"
    - code: "513500"
      name: "标普500"
    - code: "510050"
      name: "上证50ETF"
    - code: "159901"
      name: "深证100ETF"
    - code: "510500"
      name: "中证500ETF"
    - code: "513100"
      name: "纳斯达克ETF"

# ETF名称映射字典（用于快速查找）
etf_name_map:
  "159869": "游戏ETF"
  "516770": "动漫游戏ETF"
  "512980": "传媒ETF"
  "588000": "科创50ETF"
  "512720": "计算机ETF"
  "515000": "科技ETF"
  "512480": "半导体ETF"
  "516160": "新能源ETF"
  "515790": "光伏ETF"
  "515030": "新能源车ETF"
  "512690": "酒ETF"
  "159928": "消费ETF"
  "512010": "医药ETF"
  "512000": "券商ETF"
  "512800": "银行ETF"
  "512400": "有色金属ETF"
  "512760": "国防军工ETF"
  "510300": "沪深300ETF"
  "510880": "红利ETF"
  "518880": "黄金ETF"